import { Profile, ProfileFormData } from './profile-schema'

export const mockProfileFormData: ProfileFormData = {
  full_name: 'Demo User',
  email: 'demo@example.com',
  phone: '+1 (555) 123-4567',
  date_of_birth: '1990-01-15',
  employment_status: 'employed',
  monthly_income: 5000,
  fixed_expenses: 2000,
  savings_goal: 10000,
  risk_tolerance: 'moderate',
  financial_goals: ['emergency fund', 'vacation', 'home purchase'],
  preferred_currency: 'USD',
}

export const mockProfile: Profile = {
  id: 'profile-demo-1',
  user_id: 'demo-user',
  full_name: 'Demo User',
  email: 'demo@example.com',
  phone: '+1 (555) 123-4567',
  date_of_birth: '1990-01-15',
  employment_status: 'employed',
  monthly_income: 5000,
  fixed_expenses: 2000,
  savings_goal: 10000,
  risk_tolerance: 'moderate',
  financial_goals: ['emergency fund', 'vacation', 'home purchase'],
  preferred_currency: 'USD',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const mockProfiles: Profile[] = [
  mockProfile,
  {
    id: 'profile-user-2',
    user_id: 'user-2',
    full_name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1 (555) 234-5678',
    date_of_birth: '1985-05-20',
    employment_status: 'self-employed',
    monthly_income: 7500,
    fixed_expenses: 3000,
    savings_goal: 25000,
    risk_tolerance: 'aggressive',
    financial_goals: ['retirement', 'investment portfolio'],
    preferred_currency: 'USD',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'profile-user-3',
    user_id: 'user-3',
    full_name: 'Robert Johnson',
    email: 'robert@example.com',
    phone: null,
    date_of_birth: null,
    employment_status: 'unemployed',
    monthly_income: 0,
    fixed_expenses: 1000,
    savings_goal: 5000,
    risk_tolerance: 'conservative',
    financial_goals: null,
    preferred_currency: 'USD',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
]
